application: demo
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webob
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /service/.*
  script: service.app

- url: .*
  script: main.app

